{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wake.fullname" . }}-secret
  labels:
    {{- include "wake.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  vault-encryption-key: {{ default "6c1fe4e407b8911c104518103505b218" .Values.vault.encryptionKey | b64enc | quote }}
  vault-auth-secret: {{ default "5lrMXKKWCVocSrYjEYmDMOh8PCypIIVeo80fBoTomtw=" .Values.vault.authSecret | b64enc | quote }}
{{- end }}
